enum VehicleActionTypes {
    FETCH_VEHICLES_START = 'FETCH_VEHICLES_START',
    FETCH_VEHICLES_SUCCESS = 'FETCH_VEHICLES_SUCCESS',
    FETCH_VEHICLES_FAILURE = 'FETCH_VEHICLES_FAILURE',
}

export default VehicleActionTypes;
